### ISSUE TITLE
Probable bug:  Object names not highlighted when they "say" something

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#134]
I've been looking for this as a debug for a couple of days because I am reasonably sure there is one...
But the majority of things said by an object are not highlighting their name and making it clickable (so you can see who owns them).
I believe this started a few builds back but I cannot say for sure.   Sorry for being vague about this one
![Snap0001](https://user-images.githubusercontent.com/107435635/183384529-9a8c1f21-c826-4f10-8e48-e902b966a806.jpg)
.]
![Snap0004](https://user-images.githubusercontent.com/107435635/183384960-32406b17-6a89-464d-9223-5bf77a50511c.jpg)

here is another example, the sploder should show in a different color and be clickable

**Comment by MelyCosti** [comment]
@TorricRodas should be LinksForChattingObjects debug value. To try
