### ISSUE TITLE
5 low priority bits and bobs that could improve the viewer.   contributions from illi and shep

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#141]
1)profile place should persist through sessions like inventory does. Goes back to middle on relog.

2)inventory folder,  "open in new window" should behave the same as main inventory and remember its place

3)radar: box for "has notes" can we darken that, the box is faint

4) keyword alerts.. should their colour override contact set colour?   currently contact set is dominant.

5) keyword alert should have a debug sound:   KeywordsSound = 6cddbbac-31fc-2c2d-2b91-e979744abccc

**Comment by MelyCosti** [comment]
I made 5 issues from this ticket
