### ISSUE TITLE
build number in repository listing?

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#149]
Mel is it possible to put the build/commit number, either in a box on the download page (or if easier in the filename?)
It has been my experience that people have favourite builds they keep longer than others and 302 is looking to be a good one that people are happy with.  It would be good to have it listed as 302 instead of 9th Aug, which we're not so likely to remember.

**Comment by MelyCosti** [comment]
The build name will include the git revision number instead of the date
