### ISSUE TITLE
debug forgetting some settings on relog

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#152]
hi Mel..  we may have a problem with Debug not remembering settings.    illi changed AvatarNameColor in her debug, but when it relogs it reverts to default which is orange.. altho when you press Reset to default its white as I said the other day.   but anyway, that setting is lost.   I'll put it in a ticket.  I should have spotted this myself because the other day I accidently changed the colour of the logout box, but next time it had corrected itself.. meaning it hadn't kept the debug.    Could this also be related to my LSL weird colour scheme?

**Comment by MelyCosti** [comment]
@TorricRodas some of the settings are not persistant, you can see that in settings.xml

**Comment by TorricRodas** [comment]
We changed the ones that needed to persist.
