### ISSUE TITLE
Can't save a notecard

### ISSUE THREAD

**Issue by MelyCosti** [MelyCosti/Genesis-Eve#16]
Torric thinks it's about unlimited bandwith.
Need to be fixed

**Comment by TorricRodas** [comment]
It is okay today.   At tomorrows simulator meeting we need to find out how much work the region does when someone is making NCs because it is entirely reasonable that a regular laggy Sunday had more to do with problems than high bandwidths

**Comment by TorricRodas** [comment]
I think SL was having a bad time.  I have not seen this problem since
