### ISSUE TITLE
Bug? - Offline group notices, offline IM's, pay notifications and L$ balance, not updating for billy at logon

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#197]
Billy has an issue which I am sure is inventory related because of it's size (200k+).  But he never gets his offline overnight group notices, offline IM's or pay notifications.     I cannot repro this myself (my inventory is 35k) but I've seen it on his account.  If he logs into FS, he gets his stored offline notices instantly.  His L$ balance also always says 'loading' until he clicks it.     So somewhere along the way Genesis is not indicating that he is ready to receive offlines?    I'll put this in a ticket as a potential bug,

**Comment by MelyCosti** [comment]
@TorricRodas Ichanged the server calls order in the startup workflow so that these informations are loaded first

**Comment by TorricRodas** [comment]
Fixed!
