### ISSUE TITLE
Not able to save a pic in JPG or BMP format

### ISSUE THREAD

**Issue by MelyCosti** [MelyCosti/Genesis-Eve#20]

**Comment by TorricRodas** [comment]
It can be changed in Debug:    SnapshotFormat: Save snapshots in this format (0 = PNG, 1 = JPEG, 2 = BMP)
I believe JPG would be the preferred default?

**Comment by MelyCosti** [comment]
@TorricRodas I can try to make a combobox to let the user choose the format he wants. First entry will be JPEG. the last option chosen by the user will be stored in  SnapshotFormat setting

**Comment by MelyCosti** [comment]
this combox already exists, in an advanced view, I am going to remove the more /less button to let these informations always visible
