### ISSUE TITLE
ShowCameraControls: Display camera controls on login should be True

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#26]
The camera compass should be shown by default.  Advanced users only need to click the little X to remove it, but for new users this would be invaluable as learning keyboard shortcuts to views can take a while to learn.

ShowCameraControls: True

**Comment by MelyCosti** [comment]
@TorricRodas ShowCameraControls has been set to True by default.
Maybe we need a button in the bottom bar to display/hide it?
