### ISSUE TITLE
V1 Bug:  top menu, Genesis> close all dialogs shows the wrong shortcut

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#271]
Option works correctly but shortcut is to open the Advanced menu.
XL thinks the shortcut is probably  SHIFT CTRL W
![Snap0008](https://user-images.githubusercontent.com/107435635/193423615-79d0ddde-cc84-44fb-97b1-34cfad686ccd.jpg)

**Comment by MelyCosti** [comment]
Not an issue, works as it should
