### ISSUE TITLE
V1 Pre-Release, logon Message of the Day insert 

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#272]
Code to count logins and every 25th login show a link to genesisviewer.org as MOTD, where we can promote latest update, tips and tricks etc. 

This code should contain a creation date of the MOTD link and should not display at all if the current date is >12 months ahead of the creation date of the link.
This prevents the scenario where a disused address.org gets acquired by a domain re-seller for other advertising purposes.

This also gives us the opportunity to keep users up-to-date without doing a 'phone home' to a third party server, which we have already decided we should never do.

**Comment by Shep1962** [comment]
can you MOTD also include a  'do not show again' option.

**Comment by TorricRodas** [comment]
> can you MOTD also include a 'do not show again' option.

I'd rather not,   we're talking about replacing MOTD with our own..   For tips and tricks see genesisviewer.org  in every 25 to 50 or 75 logons... since dev is ongoing, we don't really want them dismissing it never to be seen again?

**Comment by MelyCosti** [comment]
@TorricRodas I propose to store a file on LC server which will be pointed by https://genesisviewer.org/motd
each line will be : <date>|motd

The viewer tries to load the file, if can't , we continue
If we can donwload, then we get the lines with <date> < today and order by <date>

counting the numbers of login will be easy.
so if logincount % 25 == 0, the viewer takes the first motd and replace the message on login screen.

Hope I was clear in my explications.

What do you think?

**Comment by TorricRodas** [comment]
> 
> What do you think?

we wanted to avoid phone home.  so we just need a one line xml that checks its creation date against todays date and doesn't display at all if the xml is more than 1 year old.   we just need to remember to reset the xml date semi regularly
