### ISSUE TITLE
V1 Bug: Download date on page always changes to today for latest version despite it being compiled days ago

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#301]
TroubleTheTribble Resident

 — Yesterday at 22:20
When I refresh the "nightly builds" page and the VERSION NUMBER (filename) does NOT change but the Last Modified DATE changes - is it still the same code?
This happens every few days and just makes me wonder.  I've not downloaded the file again to see, but thought I'd ask here as to why the date changes and if there IS actually new/updated machine code in the same name/version executable
ok, thanks.  I downloaded that the other day.  Was surprized to see it listed with today's date when I refreshed.

**Comment by MelyCosti** [comment]
@TorricRodas fixed on LC server side
