### ISSUE TITLE
V1 Cosmetic changing some default debugs to add some essential buttons on the toolbar on new installation

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#323]
ToolbarVisibleToolbarPrefs: True
ToolbarVisibleCameraControls: True
ToolbarVisibleDestinations: True      <- This needs a corresponding checkbox to be added to the Toolbar prefs panel
ToolbarVisibleActiveSpeakers: True
ToolbarVisibleAvatar: True

**Comment by Shep1962** [comment]
The toolbar 'Destination button' (ToolbarVisibleDestination), does not have a corresponding check-box in the 'change toolbar buttons' floater, so it can only be disabled with by debugsetting
Adding the (ToolbarVisibleActiveSpeakers) will be duplicating this button, as it already exists next to the 'Talk' button
I think that the 'Default Avatar button' (ToolbarVisibleAvatar) should also be included, as default for new users to SL
