### ISSUE TITLE
V2 feature.  Right click Toolbar : Add the ToolbarVisibleToolbarPrefs as a context menu on the button bar

### ISSUE THREAD

**Issue by Shep1962** [MelyCosti/Genesis-Eve#324]
Right click Toolbar : instead of having the ToolbarVisibleToolbarPrefs as a visible button by default.
How about having it as a right click context menu, similar to how FS do it. 
i.e. right click the button bar to change it.

**Comment by TorricRodas** [comment]
This is in the v2 request list
