### ISSUE TITLE
A Control to Enable Creation of LogFile and Send on Crash

### ISSUE THREAD

**Issue by XLHudson** [MelyCosti/Genesis-Eve#334]

**Comment by TorricRodas** [comment]
We have decided against this.  Being a brand new viewer, we want to build trust and have people send us logs via email. Fiddly I know cos they have to copy and email, but we want them to be in no doubt that they are volunteering to send us their logs.
It would also violate our self certification privacy policy.

Once trust is built, this is something we would reconsider, but we're just not at the stage yet, being brand new, where any information should be sent to us automatically, even if the user selects it, lest there are allegations of spyware etc.

**Comment by XLHudson** [comment]
I see related control in Debug CrashSubmitBehavior: Controls behavior when viewer crashes (0 = never send crash report, 1 = always send crash report)
