### ISSUE TITLE
channel name

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#66]
Please take a look at the channel names:   https://wiki.secondlife.com/wiki/Channel_and_Version_Requirements

I'd like to get us listed as soon as we're ready.. so I suggest we start on a Beta as we move toward a Release

**Comment by MelyCosti** [comment]
### Building a test version 
autobuild configure -cRelease -A64  -- -DUSE_FMODSTUDIO:BOOL=ON -DVIEWER_CHANNEL_BASE="Genesis" -DVIEWER_CHANNEL_TYPE="Test"

### Building a beta version 
autobuild configure -cRelease -A64  -- -DUSE_FMODSTUDIO:BOOL=ON -DVIEWER_CHANNEL_BASE="Genesis" -DVIEWER_CHANNEL_TYPE="Beta Eve"

### Building a release version 
autobuild configure -cRelease -A64  -- -DUSE_FMODSTUDIO:BOOL=ON -DVIEWER_CHANNEL_BASE="Genesis" -DVIEWER_CHANNEL_TYPE="Release"
