### ISSUE TITLE
Teleports need looking at..

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#67]
My fault for not spotting this sooner because I don't TP around much.

TP's in this viewer tend to be less reliable than  FS and LL.  An unsuccessful TP often results in a disconnect.   I believe we TP people differently from the others or have very old code.  Although TP's are not 100% in any viewer, I think if we look at how the others do it, it might help us considerably.  Suggest we look to see when Henri last modded his TP code and go from there?

**Comment by MelyCosti** [comment]
should have a look to doTeleportViaLocation
