### ISSUE TITLE
V1 Contact set name appearing  should be turn offable for those not wanting to see it. (Low 4)

### ISSUE THREAD

**Issue by TorricRodas** [MelyCosti/Genesis-Eve#92]
the contact set name appears on screen under the user name and tag and also in the chat window.   Handy as it is, Shep thinks for screen crowding we should be able to turn it off.   I think he's probably right about that.

**Comment by MelyCosti** [comment]
@TorricRodas I propose to add a checkbox on top of the local chat screen (like "show muted text") to display or not the Contact set name in local chat
